### PR TITLE
Experimental twitch integration / Debug mode

### PR DESCRIPTION
**Pull request by KoolieAid**
Client that connects to twitch is written in Rust. I may not be good at rust, so im just tryna manage

Known issues rn:
- None

Fixed issues:
- Memory leak when calling `init_runtime` and `free_handle`
- Does not call the registered callback in rust

### CODE REVIEW

**Comment by KoolieAid** [comment]
Testing C code for reference:
pls don't delete this as I use this to test the native code to test if the code interops with all languages
```c
#include <stdint.h>
#include <stdio.h>
#include <unistd.h>

extern void* init_runtime(void (*fn)());

extern void free_handle(void* context);

extern void join_channel(void* context, uint16_t ptr, int length);

extern void free_string(const char* str);

void listener(const char* const string) {
  printf("dummy::%s\n", string);
  free_string(string);
}

int main(void) {
  void* ctx = init_runtime(listener);
  
  if (ctx == NULL) {
    printf("NULL returned\n");
    return 1;
  }

  sleep(20000);
  
  free_handle(ctx);
  
  printf("end of c main\n");
  
  return 0;
}
```

**Comment by KoolieAid** [comment]
will change folderstructure, so .meta files wont interfere with cargo

**Comment by LauSnchzz** [comment]
If this is automatically off/hidden then we can keep it and merge it then have a debug mode to turn it on

**Review by LauSnchzz — APPROVED** [review]
as long as it works and its hidden and debug lang pwede ma active sure why not

**Pull request merged**
